import { baseTokens } from './baseTokens'

export const semanticTokens = {
	CNAM: {
		color: {
			border: baseTokens.color.blue.base,
			borderVariant: baseTokens.color.grey.lighten40,
			disabled: baseTokens.color.grey.lighten80,
			inverseSurface: baseTokens.color.grey.base,
			onDisabled: baseTokens.color.grey.lighten40,
			onPrimary: baseTokens.color.white.base,
			onPrimaryVariant: baseTokens.color.white.base,
			onSecondary: baseTokens.color.white.base,
			onSecondaryVariant: baseTokens.color.white.base,
			onSurface: baseTokens.color.grey.darken60,
			onSurfaceVariant: baseTokens.color.grey.base,
			overlay: baseTokens.color.grey.alpha40,
			primary: baseTokens.color.blue.base,
			primaryVariant: baseTokens.color.blue.darken40,
			secondary: baseTokens.color.cyan.darken40,
			secondaryVariant: baseTokens.color.cyan.darken60,
			surface: baseTokens.color.white.base,
			surfaceBright: baseTokens.color.blue.lighten97,
			surfaceDim: baseTokens.color.blue.lighten90,
		},
		background: {
			background: baseTokens.color.blue.lighten90,
			backgroundVariant: baseTokens.color.white.base,
			onBackground: baseTokens.color.grey.darken60,
			onBackgroundVariant: baseTokens.color.grey.lighten40,
		},
		feedback: {
			error: baseTokens.color.orange.darken20,
			errorVariant: baseTokens.color.orange.lighten80,
			info: baseTokens.color.blue.base,
			infoVariant: baseTokens.color.blue.lighten80,
			onError: baseTokens.color.white.base,
			onErrorVariant: baseTokens.color.orange.darken60,
			onInfo: baseTokens.color.white.base,
			onInfoVariant: baseTokens.color.blue.darken20,
			onSuccess: baseTokens.color.grey.darken60,
			onSuccessVariant: baseTokens.color.grey.darken60,
			onWarning: baseTokens.color.grey.darken60,
			onWarningVariant: baseTokens.color.yellow.darken60,
			success: baseTokens.color.green.base,
			successVariant: baseTokens.color.green.lighten80,
			warning: baseTokens.color.yellow.base,
			warningVariant: baseTokens.color.yellow.lighten80,
		},
		interaction: {
			darkEnabled: baseTokens.color.transparentBlue.alpha00,
			darkHover: baseTokens.color.transparentBlue.alpha08,
			darkPressed: baseTokens.color.transparentBlue.alpha20,
			darkenEnabled: baseTokens.color.transparentBlack.alpha00,
			darkenHover: baseTokens.color.transparentBlack.alpha20,
			darkenPressed: baseTokens.color.transparentBlack.alpha40,
			lightenEnabled: baseTokens.color.none,
			lightenHover: baseTokens.color.white.alpha20,
			lightenPressed: baseTokens.color.white.alpha40,
		},
	},
	ap: {
		color: {
			border: baseTokens.color.cyan.darken20,
			borderVariant: baseTokens.color.grey.lighten40,
			disabled: baseTokens.color.grey.lighten80,
			inverseSurface: baseTokens.color.grey.base,
			onDisabled: baseTokens.color.grey.lighten40,
			onPrimary: baseTokens.color.white.base,
			onPrimaryVariant: baseTokens.color.white.base,
			onSecondary: baseTokens.color.white.base,
			onSecondaryVariant: baseTokens.color.white.base,
			onSurface: baseTokens.color.grey.darken60,
			onSurfaceVariant: baseTokens.color.grey.base,
			overlay: baseTokens.color.grey.alpha40,
			primary: baseTokens.color.cyan.darken20,
			primaryVariant: baseTokens.color.cyan.darken40,
			secondary: baseTokens.color.cyan.darken60,
			secondaryVariant: baseTokens.color.cyan.darken80,
			surface: baseTokens.color.white.base,
			surfaceBright: baseTokens.color.cyan.lighten97,
			surfaceDim: baseTokens.color.cyan.lighten80,
		},
		background: {
			background: baseTokens.color.cyan.lighten97,
			backgroundVariant: baseTokens.color.white.base,
			onBackground: baseTokens.color.grey.darken60,
			onBackgroundVariant: baseTokens.color.grey.lighten40,
		},
		feedback: {
			error: baseTokens.color.red.darken20,
			errorVariant: baseTokens.color.red.lighten90,
			info: baseTokens.color.parma.darken40,
			infoVariant: baseTokens.color.parma.lighten80,
			onError: baseTokens.color.white.base,
			onErrorVariant: baseTokens.color.red.darken60,
			onInfo: baseTokens.color.white.base,
			onInfoVariant: baseTokens.color.parma.darken60,
			onSuccess: baseTokens.color.white.base,
			onSuccessVariant: baseTokens.color.forestGreen.darken60,
			onWarning: baseTokens.color.grey.darken60,
			onWarningVariant: baseTokens.color.yellow.darken60,
			success: baseTokens.color.forestGreen.base,
			successVariant: baseTokens.color.forestGreen.lighten90,
			warning: baseTokens.color.yellow.base,
			warningVariant: baseTokens.color.yellow.lighten80,
		},
		interaction: {
			darkEnabled: baseTokens.color.transparentCyan.alpha00,
			darkHover: baseTokens.color.transparentCyan.alpha08,
			darkPressed: baseTokens.color.transparentCyan.alpha18,
			darkenEnabled: baseTokens.color.transparentBlack.alpha00,
			darkenHover: baseTokens.color.transparentBlack.alpha20,
			darkenPressed: baseTokens.color.transparentBlack.alpha40,
			lightenEnabled: baseTokens.color.none,
			lightenHover: baseTokens.color.white.alpha20,
			lightenPressed: baseTokens.color.white.alpha38,
		},
	},
} as const
