import type { VariantInput } from './types'
import { buildPrimitives } from './buildPrimitives'
import { buildSemantic } from './buildSemantic'
import { buildContextual } from './buildContextual'

export function buildVariant({ colors, contextual, semanticValues, additionalContextual, spacingTokens }: VariantInput): string {
	const lines = [
		'/*',
		' * Generated from src/designTokens.',
		' * Do not edit this file manually.',
		' */',
		'',
		...buildPrimitives(colors),
		...buildSemantic(semanticValues),
		...buildContextual(contextual, additionalContextual, spacingTokens),
		'',
	]

	return `${lines.join('\n')}\n`
}
