import { cnamColorsTokens } from './cnamColors'

export const cnamSemanticTokens = {
	colors: {
		background: {
			main: cnamColorsTokens.blue.lighten90,
			surface: cnamColorsTokens.white.base,
			mainAlt: cnamColorsTokens.white.base,
			mainTer: cnamColorsTokens.grey.lighten97,
			surfaceAlt: cnamColorsTokens.blue.lighten90,
			raised: cnamColorsTokens.blue.lighten97,
			accent: cnamColorsTokens.blue.base,
			accentContrasted: cnamColorsTokens.blue.darken40,
			accentAlt: cnamColorsTokens.grey.darken80,
			info: cnamColorsTokens.blue.lighten80,
			infoSubdued: cnamColorsTokens.blue.lighten90,
			infoContrasted: cnamColorsTokens.blue.base,
			success: cnamColorsTokens.turquoise.lighten80,
			successSubdued: cnamColorsTokens.turquoise.lighten90,
			successContrasted: cnamColorsTokens.green.base,
			warning: cnamColorsTokens.yellow.lighten80,
			warningSubdued: cnamColorsTokens.yellow.lighten90,
			warningContrasted: cnamColorsTokens.yellow.base,
			error: cnamColorsTokens.orange.lighten80,
			errorSubdued: cnamColorsTokens.orange.lighten90,
			errorContrasted: cnamColorsTokens.orange.darken20,
			disabled: cnamColorsTokens.grey.lighten80,
			disabledOnDark: cnamColorsTokens.white.lighten8,
			assure: cnamColorsTokens.pink.lighten40,
			professionnel: cnamColorsTokens.cyan.lighten40,
			entreprise: cnamColorsTokens.yellow.base,
		},
		border: {
			darker: cnamColorsTokens.grey.darken60,
			base: cnamColorsTokens.grey.lighten40,
			subdued: cnamColorsTokens.grey.lighten80,
			accentPrimary: cnamColorsTokens.blue.base,
			accentPrimaryContrasted: cnamColorsTokens.blue.darken40,
			accentPrimaryOnDark: cnamColorsTokens.white.base,
			accentSecondary: cnamColorsTokens.cyan.base,
			accentSecondaryContrasted: cnamColorsTokens.cyan.darken40,
			info: cnamColorsTokens.blue.base,
			success: cnamColorsTokens.green.darken60,
			warning: cnamColorsTokens.yellow.darken60,
			error: cnamColorsTokens.orange.darken20,
			onDark: cnamColorsTokens.white.lighten70,
			disabled: cnamColorsTokens.grey.lighten80,
			disabledOnDark: cnamColorsTokens.white.lighten40,
		},
		text: {
			base: cnamColorsTokens.grey.darken60,
			accentPrimary: cnamColorsTokens.blue.base,
			accentPrimaryContrasted: cnamColorsTokens.blue.darken40,
			accentSecondary: cnamColorsTokens.cyan.darken60,
			subdued: cnamColorsTokens.grey.base,
			info: cnamColorsTokens.blue.base,
			success: cnamColorsTokens.green.darken60,
			warning: cnamColorsTokens.yellow.darken60,
			error: cnamColorsTokens.orange.darken20,
			disabled: cnamColorsTokens.grey.lighten40,
			onDark: cnamColorsTokens.white.base,
			subduedOnDark: cnamColorsTokens.white.lighten70,
			disabledOnDark: cnamColorsTokens.white.lighten40,
		},
		icon: {
			base: cnamColorsTokens.grey.darken60,
			subdued: cnamColorsTokens.grey.base,
			subduedOnDark: cnamColorsTokens.white.lighten70,
			accentPrimary: cnamColorsTokens.blue.base,
			accentPrimaryContrasted: cnamColorsTokens.blue.darken40,
			accentSecondary: cnamColorsTokens.cyan.darken40,
			info: cnamColorsTokens.blue.base,
			success: cnamColorsTokens.green.darken60,
			warning: cnamColorsTokens.yellow.darken40,
			error: cnamColorsTokens.orange.darken20,
			onDark: cnamColorsTokens.white.base,
			disabled: cnamColorsTokens.grey.lighten40,
			disabledOnDark: cnamColorsTokens.white.lighten40,
		},
		overlay: {
			fullpage: cnamColorsTokens.grey.lighten40,
			onDark: cnamColorsTokens.white.base,
			onLight: cnamColorsTokens.blue.base,
		},
		interactive: {
			selectionEnabled: cnamColorsTokens.white.base,
			selectionHover: cnamColorsTokens.blue.lighten90,
			selectionPressed: cnamColorsTokens.blue.lighten80,
			selectionSelected: cnamColorsTokens.blue.lighten90,
			selectionHoverOnSelected: cnamColorsTokens.blue.lighten80,
			selectionSelectedAccent: cnamColorsTokens.blue.base,
			selectionHoverOnSelectedAccent: cnamColorsTokens.blue.lighten20,
			selectionDisabled: cnamColorsTokens.white.base,
		},
	},
}
