import type { DatePickerCommonProps } from '../../types'

export const buildCalendarModeComplexDatePickerProps = (props: DatePickerCommonProps) => ({
	modelValue: props.modelValue,
	format: props.format,
	dateFormatReturn: props.dateFormatReturn,
	required: props.required,
	customRules: props.customRules,
	customSuccessRules: props.customSuccessRules,
	customWarningRules: props.customWarningRules,
	errorMessages: props.errorMessages,
	hasError: props.hasError,
	hasSuccess: props.hasSuccess,
	hasWarning: props.hasWarning,
	disabled: props.disabled,
	readonly: props.readonly,
	isOutlined: props.isOutlined,
	displayIcon: props.displayIcon,
	displayAppendIcon: props.displayAppendIcon,
	displayPrependIcon: props.displayPrependIcon,
	noIcon: props.noIcon,
	disableErrorHandling: props.disableErrorHandling,
	showSuccessMessages: props.showSuccessMessages,
	bgColor: props.bgColor,
	density: props.density,
	hideDetails: props.hideDetails,
	displayRange: props.displayRange,
	displayWeekendDays: props.displayWeekendDays,
	displayTodayButton: props.displayTodayButton,
	displayHolidayDays: props.displayHolidayDays,
	displayAsterisk: props.displayAsterisk,
	showWeekNumber: props.showWeekNumber,
	isBirthDate: props.isBirthDate || props.birthDate,
	textFieldActivator: props.textFieldActivator,
	title: props.title,
	autoClamp: props.autoClamp,
	label: props.label,
	maxErrors: props.maxErrors,
	placeholder: props.placeholder,
	isValidateOnBlur: props.isValidateOnBlur,
	hint: props.hint,
	persistentHint: props.persistentHint,
	period: props.period,
	useVuetifyValidation: props.useVuetifyValidation,
	rules: props.rules,
	warningMessages: props.warningMessages,
	successMessages: props.successMessages,
})
