import { type Ref } from 'vue'
import type { DatePickerCommonProps } from '../types'

export const buildSharedDateTextInputProps = (
	props: DatePickerCommonProps,
	labelWithAsterisk: Ref<string | undefined>,
	errorMessages: Ref<string[]>,
	warningMessages: Ref<string[]>,
	successMessages: Ref<string[]>,
) => ({
	'date-format-return': props.dateFormatReturn,
	'format': props.format,
	'label': labelWithAsterisk.value,
	'placeholder': props.placeholder,
	'required': props.required,
	'custom-rules': props.customRules,
	'custom-success-rules': props.customSuccessRules,
	'custom-warning-rules': props.customWarningRules,
	'disabled': props.disabled,
	'readonly': props.readonly,
	'disable-click-button': false,
	'is-outlined': props.isOutlined,
	'display-icon': props.displayIcon,
	'display-append-icon': props.displayAppendIcon,
	'display-prepend-icon': props.displayPrependIcon,
	'no-icon': props.noIcon,
	'disable-error-handling': props.disableErrorHandling,
	'show-success-messages': props.showSuccessMessages,
	'bg-color': props.bgColor,
	'density': props.density,
	'hide-details': props.hideDetails,
	'auto-clamp': props.autoClamp,
	'error-messages': errorMessages.value,
	'has-error': props.hasError,
	'has-warning': props.hasWarning,
	'has-success': props.hasSuccess,
	'warning-messages': warningMessages.value,
	'success-messages': successMessages.value,
	'display-asterisk': props.displayAsterisk,
	'is-validate-on-blur': props.isValidateOnBlur,
	'max-errors': props.maxErrors,
	'title': props.title || props.placeholder || undefined,
	'hint': props.hint,
	'persistent-hint': props.persistentHint,
})
