import { apColorsTokens } from './apColors'

export const apSemanticTokens = {
	colors: {
		background: {
			main: apColorsTokens.cyan.lighten97,
			surface: apColorsTokens.white.base,
			mainAlt: apColorsTokens.white.base,
			surfaceAlt: apColorsTokens.cyan.lighten80,
			raised: apColorsTokens.cyan.lighten97,
			accent: apColorsTokens.cyan.darken20,
			accentContrasted: apColorsTokens.cyan.darken60,
			accentAlt: apColorsTokens.grey.base,
			info: apColorsTokens.blue.lighten80,
			infoSubdued: apColorsTokens.blue.lighten90,
			infoContrasted: apColorsTokens.parma.darken40,
			success: apColorsTokens.forestGreen.lighten80,
			successSubdued: apColorsTokens.forestGreen.lighten90,
			successContrasted: apColorsTokens.forestGreen.base,
			warning: apColorsTokens.yellow.lighten80,
			warningSubdued: apColorsTokens.yellow.lighten90,
			warningContrasted: apColorsTokens.yellow.base,
			error: apColorsTokens.red.lighten80,
			errorSubdued: apColorsTokens.red.lighten90,
			errorContrasted: apColorsTokens.red.darken20,
			disabled: apColorsTokens.grey.lighten80,
			disabledOnDark: apColorsTokens.white.lighten8,
			assure: apColorsTokens.pink.lighten40,
			professionnel: apColorsTokens.cyan.lighten40,
			entreprise: apColorsTokens.yellow.base,
		},
		border: {
			darker: apColorsTokens.grey.darken60,
			base: apColorsTokens.grey.lighten40,
			subdued: apColorsTokens.grey.lighten80,
			accentPrimary: apColorsTokens.cyan.darken20,
			accentPrimaryContrasted: apColorsTokens.cyan.darken40,
			accentPrimaryOnDark: apColorsTokens.white.base,
			accentSecondary: apColorsTokens.cyan.darken60,
			accentSecondaryContrasted: apColorsTokens.cyan.darken40,
			info: apColorsTokens.parma.darken40,
			success: apColorsTokens.forestGreen.base,
			warning: apColorsTokens.yellow.darken60,
			error: apColorsTokens.red.darken20,
			onDark: apColorsTokens.white.lighten70,
			disabled: apColorsTokens.grey.lighten80,
			disabledOnDark: apColorsTokens.white.lighten40,
		},
		text: {
			base: apColorsTokens.grey.darken60,
			accentPrimary: apColorsTokens.cyan.darken20,
			accentPrimaryContrasted: apColorsTokens.cyan.darken40,
			accentSecondary: apColorsTokens.cyan.darken60,
			subdued: apColorsTokens.grey.base,
			info: apColorsTokens.parma.darken40,
			success: apColorsTokens.forestGreen.base,
			warning: apColorsTokens.yellow.darken60,
			error: apColorsTokens.red.darken20,
			disabled: apColorsTokens.grey.lighten40,
			onDark: apColorsTokens.white.base,
			subduedOnDark: apColorsTokens.white.lighten70,
			disabledOnDark: apColorsTokens.white.lighten40,
		},
		icon: {
			base: apColorsTokens.grey.darken60,
			subdued: apColorsTokens.grey.base,
			subduedOnDark: apColorsTokens.white.lighten70,
            accentPrimary: apColorsTokens.cyan.darken20,
            accentPrimaryContrasted: apColorsTokens.cyan.darken40,
            accentSecondary: apColorsTokens.cyan.darken80,
			info: apColorsTokens.parma.darken40,
			success: apColorsTokens.forestGreen.darken60,
			warning: apColorsTokens.yellow.darken60,
			error: apColorsTokens.red.darken20,
			onDark: apColorsTokens.white.base,
			disabled: apColorsTokens.grey.lighten40,
			disabledOnDark: apColorsTokens.white.lighten40,
		},
		overlay: {
			fullpage: apColorsTokens.grey.darken60,
			onDark: apColorsTokens.cyan.darken40,
			onLight: apColorsTokens.white.base,
		},
		interactive: {
			selectionEnabled: apColorsTokens.white.base,
			selectionHover: apColorsTokens.blue.lighten80,
			selectionPressed: apColorsTokens.blue.lighten60,
			selectionSelected: apColorsTokens.blue.lighten80,
			selectionHoverOnSelected: apColorsTokens.blue.lighten60,
			selectionselectedAccent: apColorsTokens.cyan.darken20,
			selectionHoverOnSelectedAccent: apColorsTokens.cyan.lighten20,
			selectionDisabled: apColorsTokens.white.base,
		},
	},
}
