import {apColorsTokensNew} from './apColorsNew'

export const apSemanticTokens = {
    colors: {
        background: {
            main: apColorsTokensNew.cyan.lighten97,
            surface: apColorsTokensNew.white.base,
            mainAlt: apColorsTokensNew.white.base,
            surfaceAlt: apColorsTokensNew.blue.lighten90,
            raised: apColorsTokensNew.blue.lighten97,
            accent: apColorsTokensNew.cyan.darken20,
            accentContrasted: apColorsTokensNew.cyan.darken60,
            accentAlt: apColorsTokensNew.grey.base,
            info: apColorsTokensNew.blue.lighten80,
            infoSubdued: apColorsTokensNew.blue.lighten90,
            infoContrasted: apColorsTokensNew.parma.darken40,
            success: apColorsTokensNew.forestGreen.lighten80,
            successSubdued: apColorsTokensNew.forestGreen.lighten90,
            successContrasted: apColorsTokensNew.forestGreen.base,
            warning: apColorsTokensNew.yellow.lighten80,
            warningSubdued: apColorsTokensNew.yellow.lighten90,
            warningContrasted: apColorsTokensNew.yellow.base,
            error: apColorsTokensNew.red.lighten80,
            errorSubdued: apColorsTokensNew.red.lighten90,
            errorContrasted: apColorsTokensNew.red.darken20,
            disabled: apColorsTokensNew.grey.lighten80,
            disabledOnDark: apColorsTokensNew.white.lighten8,
            assure: apColorsTokensNew.pink.lighten40,
            professionnel: apColorsTokensNew.cyan.lighten40,
            entreprise: apColorsTokensNew.yellow.base,
        },
        border: {
            darker: apColorsTokensNew.grey.darken60,
            base: apColorsTokensNew.grey.lighten40,
            subdued: apColorsTokensNew.grey.lighten80,
            accent: apColorsTokensNew.cyan.darken20,
            accentContrasted: apColorsTokensNew.cyan.darken40,
            accentOnDark: apColorsTokensNew.white.base,
            info: apColorsTokensNew.parma.darken40,
            success: apColorsTokensNew.forestGreen.base,
            warning: apColorsTokensNew.yellow.darken60,
            error: apColorsTokensNew.red.darken20,
            onDark: apColorsTokensNew.white.lighten70,
            disabled: apColorsTokensNew.grey.lighten80,
            disabledOnDark: apColorsTokensNew.white.lighten40,
        },
        text: {
            base: apColorsTokensNew.grey.darken60,
            accent: apColorsTokensNew.cyan.darken20,
            accentContrasted: apColorsTokensNew.cyan.darken40,
            subdued: apColorsTokensNew.grey.base,
            info: apColorsTokensNew.parma.darken40,
            success: apColorsTokensNew.forestGreen.base,
            warning: apColorsTokensNew.yellow.darken60,
            error: apColorsTokensNew.red.darken20,
            disabled: apColorsTokensNew.grey.lighten40,
            onDark: apColorsTokensNew.white.base,
            subduedOnDark: apColorsTokensNew.white.lighten70,
            disabledOnDark: apColorsTokensNew.white.lighten40,
        },
        icon: {
            base: apColorsTokensNew.grey.darken60,
            subdued: apColorsTokensNew.grey.base,
            subduedOnDark: apColorsTokensNew.white.lighten70,
            accent: apColorsTokensNew.cyan.darken20,
            accentContrasted: apColorsTokensNew.cyan.darken40,
            info: apColorsTokensNew.parma.darken40,
            success: apColorsTokensNew.forestGreen.darken60,
            warning: apColorsTokensNew.yellow.darken60,
            error: apColorsTokensNew.red.darken20,
            onDark: apColorsTokensNew.white.base,
            disabled: apColorsTokensNew.grey.lighten40,
            disabledOnDark: apColorsTokensNew.white.lighten40,
        },
        overlay: {
            fullpage: apColorsTokensNew.grey.darken60,
            onDark: apColorsTokensNew.cyan.darken40,
            onLight: apColorsTokensNew.white.base,
        },
        interactive: {
            default: apColorsTokensNew.white.base,
            hover: apColorsTokensNew.cyan.lighten90,
            pressed: apColorsTokensNew.cyan.lighten80,
            focus: apColorsTokensNew.blue.lighten90,
            disabled: apColorsTokensNew.white.base,
            hoverOnSelected: apColorsTokensNew.blue.lighten80,
        },
    },
}
