import { paColorsTokens } from './paColors'

export const paSemanticTokens = {
	colors: {
		background: {
			main: paColorsTokens.blue.lighten90,
			surface: paColorsTokens.white.base,
			mainAlt: paColorsTokens.white.base,
			surfaceAlt: paColorsTokens.blue.lighten90,
			raised: paColorsTokens.blue.lighten97,
			accent: paColorsTokens.blue.base,
			accentContrasted: paColorsTokens.blue.darken40,
			accentAlt: paColorsTokens.grey.darken80,
			info: paColorsTokens.blue.lighten80,
			infoSubdued: paColorsTokens.blue.lighten90,
			infoContrasted: paColorsTokens.blue.base,
			success: paColorsTokens.orange.darken40,
			successSubdued: paColorsTokens.turquoise.lighten90,
			successContrasted: paColorsTokens.green.base,
			warning: paColorsTokens.yellow.lighten80,
			warningSubdued: paColorsTokens.yellow.lighten90,
			warningContrasted: paColorsTokens.yellow.base,
			error: paColorsTokens.orange.lighten80,
			errorSubdued: paColorsTokens.orange.lighten90,
			errorContrasted: paColorsTokens.orange.darken20,
			disabled: paColorsTokens.grey.lighten80,
			disabledOnDark: paColorsTokens.white.lighten8,
			assure: paColorsTokens.pink.lighten40,
			professionnel: paColorsTokens.cyan.lighten40,
			entreprise: paColorsTokens.yellow.base,
		},
		border: {
			darker: paColorsTokens.grey.darken60,
			base: paColorsTokens.grey.lighten40,
			subdued: paColorsTokens.grey.lighten80,
			accentPrimary: paColorsTokens.blue.base,
			accentPrimaryContrasted: paColorsTokens.blue.darken40,
			accentPrimaryOnDark: paColorsTokens.white.base,
			accentSecondary: paColorsTokens.cyan.base,
			accentSecondaryContrasted: paColorsTokens.cyan.darken40,
			info: paColorsTokens.blue.base,
			success: paColorsTokens.green.darken60,
			warning: paColorsTokens.yellow.darken60,
			error: paColorsTokens.orange.darken20,
			onDark: paColorsTokens.white.lighten70,
			disabled: paColorsTokens.grey.lighten80,
			disabledOnDark: paColorsTokens.white.lighten40,
		},
		text: {
			base: paColorsTokens.grey.darken60,
			accentPrimary: paColorsTokens.blue.base,
			accentPrimaryContrasted: paColorsTokens.blue.darken40,
			accentSecondary: paColorsTokens.cyan.darken40,
			subdued: paColorsTokens.grey.base,
			info: paColorsTokens.blue.base,
			success: paColorsTokens.green.darken60,
			warning: paColorsTokens.yellow.darken60,
			error: paColorsTokens.orange.darken20,
			disabled: paColorsTokens.grey.lighten40,
			onDark: paColorsTokens.white.base,
			subduedOnDark: paColorsTokens.white.lighten70,
			disabledOnDark: paColorsTokens.white.lighten40,
		},
		icon: {
			base: paColorsTokens.grey.darken60,
			subdued: paColorsTokens.grey.base,
			subduedOnDark: paColorsTokens.white.lighten70,
			accentPrimary: paColorsTokens.blue.base,
			accentPrimaryContrasted: paColorsTokens.blue.darken40,
			accentSecondary: paColorsTokens.cyan.darken40,
			info: paColorsTokens.blue.base,
			success: paColorsTokens.green.darken60,
			warning: paColorsTokens.yellow.darken60,
			error: paColorsTokens.orange.darken20,
			onDark: paColorsTokens.white.base,
			disabled: paColorsTokens.grey.lighten40,
			disabledOnDark: paColorsTokens.white.lighten40,
		},
		overlay: {
			fullpage: paColorsTokens.grey.lighten40,
			onDark: paColorsTokens.white.base,
			onLight: paColorsTokens.blue.base,
		},
		interactive: {
			selectionEnabled: paColorsTokens.white.base,
			selectionHover: paColorsTokens.blue.lighten90,
			selectionPressed: paColorsTokens.blue.lighten80,
			selectionSelected: paColorsTokens.blue.lighten90,
			selectionHoverOnSelected: paColorsTokens.blue.lighten80,
			selectionselectedAccent: paColorsTokens.blue.base,
			selectionHoverOnSelectedAccent: paColorsTokens.blue.lighten20,
			selectionDisabled: paColorsTokens.white.base,
		},
	},
}
