export interface IconItem {
	name: string
	noBackground?: boolean
}

export const iconList: IconItem[] = [
	{ name: 'structures' },
	{ name: 'applications' },
	{ name: 'notifications' },
	{ name: 'deconnexion' },
	{ name: 'home' },
	{ name: 'homeSquare' },
	{ name: 'menu' },
	{ name: 'menuSquare' },
	{ name: 'aide' },
	{ name: 'plus' },
	{ name: 'croix' },
	{ name: 'check' },
	{ name: 'information' },
	{ name: 'telechargement' },
	{ name: 'upload' },
	{ name: 'modifier' },
	{ name: 'pieceJointe' },
	{ name: 'poubelle' },
	{ name: 'rechercher' },
	{ name: 'informationPersonnage' },
	{ name: 'sensInterdit' },
	{ name: 'exclamation' },
	{ name: 'ampoule' },
	{ name: 'courrier' },
	{ name: 'message' },
	{ name: 'pdf' },
	{ name: 'csv' },
	{ name: 'xls' },
	{ name: 'convention' },
	{ name: 'paiements' },
	{ name: 'commandes' },
	{ name: 'patientele' },
	{ name: 'horlogeFlecheDroite' },
	{ name: 'horlogeFlecheGauche' },
	{ name: 'releveHonoraires' },
	{ name: 'horairesCabinet' },
	{ name: 'releveActivite' },
	{ name: 'checkText' },
	{ name: 'checkDocument' },
	{ name: 'documentPill' },
	{ name: 'noPill' },
	{ name: 'declarationAstreinte' },
	{ name: 'declarationInserm' },
	{ name: 'ordonnanceNumerique' },
	{ name: 'optam' },
	{ name: 'optam2' },
	{ name: 'arrowShield' },
	{ name: 'echangeServiceMedical' },
	{ name: 'adac' },
	{ name: 'perteActiviteCovid' },
	{ name: 'stethoscope' },
	{ name: 'grossesse' },
	{ name: 'ambulance' },
	{ name: 'demandeTransport' },
	{ name: 'demandeMedicament' },
	{ name: 'checkEstomac' },
	{ name: 'contactCovid' },
	{ name: 'oeil' },
	{ name: 'parapluie' },
	{ name: 'cible' },
	{ name: 'brasCasse' },
	{ name: 'chute' },
	{ name: 'chuteCasque' },
	{ name: 'seringue' },
	{ name: 'vaccination' },
	{ name: 'infirmier' },
	{ name: 'stylo' },
	{ name: 'pillules' },
	{ name: 'pillules2' },
	{ name: 'cadenas' },
	{ name: 'prescription' },
	{ name: 'personneAgee' },
	{ name: 'nuageEchange' },
	{ name: 'mainCoeur' },
	{ name: 'localisation' },
	{ name: 'centPourcent' },
	{ name: 'hourglass' },
	{ name: 'qrCode' },
	{ name: 'qrCode2' },
	{ name: 'link' },
	{ name: 'link2' },
	{ name: 'sidep' },
	{ name: 'dmp' },
	{ name: 'document' },
	{ name: 'touch' },
	{ name: 'phone' },
	{ name: 'photo' },
	{ name: 'video' },
	{ name: 'accessibility' },
	{ name: 'homeChar' },
	{ name: 'h' },
	{ name: 'ma' },
	{ name: 'sa' },
	{ name: 'readOnly' },
	{ name: 'chronometer' },
	{ name: 'microphone' },
	{ name: 'bonus' },
	{ name: 'userFolder' },
	{ name: 'toothShield' },
	{ name: 'bell' },
	{ name: 'notePencil' },
	{ name: 'signature' },
	{ name: 'signature2' },
	{ name: 'shieldPlus' },
	{ name: 'delegation' },
	{ name: 'attele' },
	{
		name: 'chevronLeft',
		noBackground: true,
	},
	{
		name: 'chevronRight',
		noBackground: true,
	},
	{
		name: 'chevronUp',
		noBackground: true,
	},
	{
		name: 'chevronDown',
		noBackground: true,
	},
	{
		name: 'triangleUp',
		noBackground: true,
	},
	{
		name: 'triangleDown',
		noBackground: true,
	},
	{
		name: 'circle',
		noBackground: true,
	},
	{
		name: 'calendar',
		noBackground: true,
	},
	{
		name: 'chrono',
		noBackground: true,
	},
	{
		name: 'discussion',
		noBackground: true,
	},
	{
		name: 'boite',
		noBackground: true,
	},
	{
		name: 'ecrire',
		noBackground: true,
	},
	{
		name: 'horlogeFlecheDroiteNoCircle',
		noBackground: true,
	},
	{
		name: 'bulleGauche',
		noBackground: true,
	},
	{
		name: 'bulleDroite',
		noBackground: true,
	},
	{
		name: 'closeNoCircle',
		noBackground: true,
	},
	{
		name: 'stats',
		noBackground: true,
	},
	{
		name: 'trashNoCircle',
		noBackground: true,
	},
	{
		name: 'pencilNoCircle',
		noBackground: true,
	},
	{
		name: 'printNoCircle',
		noBackground: true,
	},
	{
		name: 'basketNoCircle',
		noBackground: true,
	},
	{
		name: 'folder',
		noBackground: true,
	},
	{
		name: 'copy',
		noBackground: true,
	},
	{
		name: 'bus',
		noBackground: true,
	},
	{
		name: 'carPerson',
		noBackground: true,
	},
	{
		name: 'planeBoat',
		noBackground: true,
	},
	{
		name: 'taxi',
		noBackground: true,
	},
	{
		name: 'ambulanceNoCircle',
		noBackground: true,
	},
	{
		name: 'arrowLeft',
		noBackground: true,
	},
	{
		name: 'arrowRight',
		noBackground: true,
	},
	{
		name: 'diamondNoCircle',
		noBackground: true,
	},
]
