export const indicatifs = [
	{ code: '+1', country: 'USA/Canada', countryFr: 'États-Unis/Canada', abbreviation: 'US/CA', phoneLength: 10, mask: '### ### ####' },
	{ code: '+7', country: 'Russia/Kazakhstan', countryFr: 'Russie/Kazakhstan', abbreviation: 'RU/KZ', phoneLength: 10, mask: '### ### ## ##' },
	{ code: '+20', country: 'Egypt', countryFr: 'Égypte', abbreviation: 'EG', phoneLength: 9, mask: '### ### ####' },
	{ code: '+27', country: 'South Africa', countryFr: 'Afrique du Sud', abbreviation: 'ZA', phoneLength: 9, mask: '### ### ####' },
	{ code: '+30', country: 'Greece', countryFr: 'Grèce', abbreviation: 'GR', phoneLength: 10, mask: '### ### ####' },
	{ code: '+31', country: 'Netherlands', countryFr: 'Pays-Bas', abbreviation: 'NL', phoneLength: 9, mask: '## ### ####' },
	{ code: '+32', country: 'Belgium', countryFr: 'Belgique', abbreviation: 'BE', phoneLength: 9, mask: '### ### ###' },
	{ code: '+33', country: 'France', countryFr: 'France', abbreviation: 'FR', phoneLength: 10, mask: '## ## ## ## ##' },
	{ code: '+34', country: 'Spain', countryFr: 'Espagne', abbreviation: 'ES', phoneLength: 9, mask: '### ### ###' },
	{ code: '+36', country: 'Hungary', countryFr: 'Hongrie', abbreviation: 'HU', phoneLength: 9, mask: '## ### ####' },
	{ code: '+39', country: 'Italy', countryFr: 'Italie', abbreviation: 'IT', phoneLength: 10, mask: '### ### ####' },
	{ code: '+40', country: 'Romania', countryFr: 'Roumanie', abbreviation: 'RO', phoneLength: 9, mask: '### ### ###' },
	{ code: '+41', country: 'Switzerland', countryFr: 'Suisse', abbreviation: 'CH', phoneLength: 9, mask: '## ### ## ##' },
	{ code: '+44', country: 'United Kingdom', countryFr: 'Royaume-Uni', abbreviation: 'GB', phoneLength: 10, mask: '#### ### ####' },
	{ code: '+45', country: 'Denmark', countryFr: 'Danemark', abbreviation: 'DK', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+46', country: 'Sweden', countryFr: 'Suède', abbreviation: 'SE', phoneLength: 9, mask: '## ### ## ##' },
	{ code: '+47', country: 'Norway', countryFr: 'Norvège', abbreviation: 'NO', phoneLength: 8, mask: '### ## ###' },
	{ code: '+48', country: 'Poland', countryFr: 'Pologne', abbreviation: 'PL', phoneLength: 9, mask: '### ### ###' },
	{ code: '+49', country: 'Germany', countryFr: 'Allemagne', abbreviation: 'DE', phoneLength: 10, mask: '#### ### ####' },
	{ code: '+51', country: 'Peru', countryFr: 'Pérou', abbreviation: 'PE', phoneLength: 9, mask: '### ### ###' },
	{ code: '+52', country: 'Mexico', countryFr: 'Mexique', abbreviation: 'MX', phoneLength: 10, mask: '## #### ####' },
	{ code: '+53', country: 'Cuba', countryFr: 'Cuba', abbreviation: 'CU', phoneLength: 8, mask: '### ### ###' },
	{ code: '+54', country: 'Argentina', countryFr: 'Argentine', abbreviation: 'AR', phoneLength: 10, mask: '### ### ####' },
	{ code: '+55', country: 'Brazil', countryFr: 'Brésil', abbreviation: 'BR', phoneLength: 11, mask: '## ##### ####' },
	{ code: '+56', country: 'Chile', countryFr: 'Chili', abbreviation: 'CL', phoneLength: 9, mask: '## #### ####' },
	{ code: '+57', country: 'Colombia', countryFr: 'Colombie', abbreviation: 'CO', phoneLength: 10, mask: '### ### ####' },
	{ code: '+58', country: 'Venezuela', countryFr: 'Venezuela', abbreviation: 'VE', phoneLength: 10, mask: '### ### ####' },
	{ code: '+60', country: 'Malaysia', countryFr: 'Malaisie', abbreviation: 'MY', phoneLength: 10, mask: '## ### ####' },
	{ code: '+61', country: 'Australia', countryFr: 'Australie', abbreviation: 'AU', phoneLength: 9, mask: '### ### ###' },
	{ code: '+62', country: 'Indonesia', countryFr: 'Indonésie', abbreviation: 'ID', phoneLength: 10, mask: '### ### ####' },
	{ code: '+63', country: 'Philippines', countryFr: 'Philippines', abbreviation: 'PH', phoneLength: 10, mask: '### ### ####' },
	{ code: '+64', country: 'New Zealand', countryFr: 'Nouvelle-Zélande', abbreviation: 'NZ', phoneLength: 9, mask: '### ### ###' },
	{ code: '+65', country: 'Singapore', countryFr: 'Singapour', abbreviation: 'SG', phoneLength: 8, mask: '#### ####' },
	{ code: '+66', country: 'Thailand', countryFr: 'Thaïlande', abbreviation: 'TH', phoneLength: 9, mask: '### ### ###' },
	{ code: '+81', country: 'Japan', countryFr: 'Japon', abbreviation: 'JP', phoneLength: 10, mask: '## #### ####' },
	{ code: '+82', country: 'South Korea', countryFr: 'Corée du Sud', abbreviation: 'KR', phoneLength: 10, mask: '## #### ####' },
	{ code: '+84', country: 'Vietnam', countryFr: 'Vietnam', abbreviation: 'VN', phoneLength: 9, mask: '## ### ####' },
	{ code: '+86', country: 'China', countryFr: 'Chine', abbreviation: 'CN', phoneLength: 11, mask: '### #### ####' },
	{ code: '+90', country: 'Turkey', countryFr: 'Turquie', abbreviation: 'TR', phoneLength: 10, mask: '### ### ## ##' },
	{ code: '+91', country: 'India', countryFr: 'Inde', abbreviation: 'IN', phoneLength: 10, mask: '##### #####' },
	{ code: '+92', country: 'Pakistan', countryFr: 'Pakistan', abbreviation: 'PK', phoneLength: 10, mask: '### #### ####' },
	{ code: '+93', country: 'Afghanistan', countryFr: 'Afghanistan', abbreviation: 'AF', phoneLength: 9, mask: '## ### ####' },
	{ code: '+94', country: 'Sri Lanka', countryFr: 'Sri Lanka', abbreviation: 'LK', phoneLength: 9, mask: '### ### ####' },
	{ code: '+95', country: 'Myanmar', countryFr: 'Myanmar', abbreviation: 'MM', phoneLength: 9, mask: '## ### ###' },
	{ code: '+98', country: 'Iran', countryFr: 'Iran', abbreviation: 'IR', phoneLength: 10, mask: '### ### ####' },
	{ code: '+212', country: 'Morocco', countryFr: 'Maroc', abbreviation: 'MA', phoneLength: 9, mask: '### #### ###' },
	{ code: '+213', country: 'Algeria', countryFr: 'Algérie', abbreviation: 'DZ', phoneLength: 9, mask: '### ### ####' },
	{ code: '+216', country: 'Tunisia', countryFr: 'Tunisie', abbreviation: 'TN', phoneLength: 8, mask: '## ### ###' },
	{ code: '+218', country: 'Libya', countryFr: 'Libye', abbreviation: 'LY', phoneLength: 9, mask: '### ### ###' },
	{ code: '+262', country: 'Réunion', countryFr: 'Réunion', abbreviation: 'FR', phoneLength: 9, mask: '### ### ###' },
	{ code: '+508', country: 'Saint Pierre and Miquelon', countryFr: 'Saint-Pierre-et-Miquelon', abbreviation: 'FR', phoneLength: 6, mask: '## ## ##' },
	{ code: '+590', country: 'Guadeloupe', countryFr: 'Guadeloupe', abbreviation: 'FR', phoneLength: 9, mask: '### ### ###' },
	{ code: '+594', country: 'French Guiana', countryFr: 'Guyane française', abbreviation: 'FR', phoneLength: 9, mask: '### ### ###' },
	{ code: '+596', country: 'Martinique', countryFr: 'Martinique', abbreviation: 'FR', phoneLength: 9, mask: '### ### ###' },
	{ code: '+687', country: 'New Caledonia', countryFr: 'Nouvelle-Calédonie', abbreviation: 'FR', phoneLength: 6, mask: '## ## ##' },
	{ code: '+689', country: 'French Polynesia', countryFr: 'Polynésie française', abbreviation: 'FR', phoneLength: 6, mask: '## ## ##' },
	{ code: '+220', country: 'Gambia', countryFr: 'Gambie', abbreviation: 'GM', phoneLength: 8, mask: '### ## ##' },
	{ code: '+221', country: 'Senegal', countryFr: 'Sénégal', abbreviation: 'SN', phoneLength: 9, mask: '## ### ####' },
	{ code: '+222', country: 'Mauritania', countryFr: 'Mauritanie', abbreviation: 'MR', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+223', country: 'Mali', countryFr: 'Mali', abbreviation: 'ML', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+224', country: 'Guinea', countryFr: 'Guinée', abbreviation: 'GN', phoneLength: 9, mask: '## ### ####' },
	{ code: '+225', country: 'Ivory Coast', countryFr: 'Côte d\'Ivoire', abbreviation: 'CI', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+226', country: 'Burkina Faso', countryFr: 'Burkina Faso', abbreviation: 'BF', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+227', country: 'Niger', countryFr: 'Niger', abbreviation: 'NE', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+228', country: 'Togo', countryFr: 'Togo', abbreviation: 'TG', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+229', country: 'Benin', countryFr: 'Bénin', abbreviation: 'BJ', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+230', country: 'Mauritius', countryFr: 'Maurice', abbreviation: 'MU', phoneLength: 7, mask: '### ####' },
	{ code: '+231', country: 'Liberia', countryFr: 'Libéria', abbreviation: 'LR', phoneLength: 7, mask: '## ### ###' },
	{ code: '+232', country: 'Sierra Leone', countryFr: 'Sierra Leone', abbreviation: 'SL', phoneLength: 8, mask: '## #### ####' },
	{ code: '+233', country: 'Ghana', countryFr: 'Ghana', abbreviation: 'GH', phoneLength: 9, mask: '### ### ###' },
	{ code: '+234', country: 'Nigeria', countryFr: 'Nigéria', abbreviation: 'NG', phoneLength: 8, mask: '### ### ###' },
	{ code: '+235', country: 'Chad', countryFr: 'Tchad', abbreviation: 'TD', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+236', country: 'Central African Republic', countryFr: 'République centrafricaine', abbreviation: 'CF', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+237', country: 'Cameroon', countryFr: 'Cameroun', abbreviation: 'CM', phoneLength: 9, mask: '## ### ####' },
	{ code: '+238', country: 'Cape Verde', countryFr: 'Cap-Vert', abbreviation: 'CV', phoneLength: 7, mask: '### ####' },
	{ code: '+239', country: 'Sao Tome and Principe', countryFr: 'São Tomé-et-Principe', abbreviation: 'ST', phoneLength: 7, mask: '### ####' },
	{ code: '+240', country: 'Equatorial Guinea', countryFr: 'Guinée équatoriale', abbreviation: 'GQ', phoneLength: 9, mask: '### ### ####' },
	{ code: '+241', country: 'Gabon', countryFr: 'Gabon', abbreviation: 'GA', phoneLength: 9, mask: '## ### ####' },
	{ code: '+242', country: 'Republic of the Congo', countryFr: 'République du Congo', abbreviation: 'CG', phoneLength: 9, mask: '## ### ####' },
	{ code: '+243', country: 'Democratic Republic of the Congo', countryFr: 'République démocratique du Congo', abbreviation: 'CD', phoneLength: 9, mask: '### ### ####' },
	{ code: '+244', country: 'Angola', countryFr: 'Angola', abbreviation: 'AO', phoneLength: 9, mask: '### ### ####' },
	{ code: '+245', country: 'Guinea-Bissau', countryFr: 'Guinée-Bissau', abbreviation: 'GW', phoneLength: 7, mask: '### ####' },
	{ code: '+248', country: 'Seychelles', countryFr: 'Seychelles', abbreviation: 'SC', phoneLength: 7, mask: '### ####' },
	{ code: '+249', country: 'Sudan', countryFr: 'Soudan', abbreviation: 'SD', phoneLength: 9, mask: '### ### ####' },
	{ code: '+250', country: 'Rwanda', countryFr: 'Rwanda', abbreviation: 'RW', phoneLength: 9, mask: '### ### ###' },
	{ code: '+251', country: 'Ethiopia', countryFr: 'Éthiopie', abbreviation: 'ET', phoneLength: 9, mask: '### ### ###' },
	{ code: '+252', country: 'Somalia', countryFr: 'Somalie', abbreviation: 'SO', phoneLength: 8, mask: '### ### ##' },
	{ code: '+253', country: 'Djibouti', countryFr: 'Djibouti', abbreviation: 'DJ', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+254', country: 'Kenya', countryFr: 'Kenya', abbreviation: 'KE', phoneLength: 9, mask: '### ### ###' },
	{ code: '+255', country: 'Tanzania', countryFr: 'Tanzanie', abbreviation: 'TZ', phoneLength: 9, mask: '### ### ###' },
	{ code: '+256', country: 'Uganda', countryFr: 'Ouganda', abbreviation: 'UG', phoneLength: 9, mask: '### ### ###' },
	{ code: '+257', country: 'Burundi', countryFr: 'Burundi', abbreviation: 'BI', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+258', country: 'Mozambique', countryFr: 'Mozambique', abbreviation: 'MZ', phoneLength: 9, mask: '## ### ####' },
	{ code: '+260', country: 'Zambia', countryFr: 'Zambie', abbreviation: 'ZM', phoneLength: 9, mask: '### ### ###' },
	{ code: '+261', country: 'Madagascar', countryFr: 'Madagascar', abbreviation: 'MG', phoneLength: 9, mask: '## ## ###' },
	{ code: '+263', country: 'Zimbabwe', countryFr: 'Zimbabwe', abbreviation: 'ZW', phoneLength: 9, mask: '### ### ###' },
	{ code: '+264', country: 'Namibia', countryFr: 'Namibie', abbreviation: 'NA', phoneLength: 9, mask: '### ### ###' },
	{ code: '+265', country: 'Malawi', countryFr: 'Malawi', abbreviation: 'MW', phoneLength: 9, mask: '### ### ###' },
	{ code: '+266', country: 'Lesotho', countryFr: 'Lesotho', abbreviation: 'LS', phoneLength: 8, mask: '## ### ###' },
	{ code: '+267', country: 'Botswana', countryFr: 'Botswana', abbreviation: 'BW', phoneLength: 8, mask: '## ### ###' },
	{ code: '+268', country: 'Eswatini', countryFr: 'Eswatini', abbreviation: 'SZ', phoneLength: 9, mask: '### ### ###' },
	{ code: '+269', country: 'Comoros', countryFr: 'Comores', abbreviation: 'KM', phoneLength: 7, mask: '### ####' },
]
