export const indicatifs = [
	{ code: '+1', country: 'USA/Canada', phoneLength: 10, mask: '###-###-####' },
	{ code: '+7', country: 'Russia/Kazakhstan', phoneLength: 10, mask: '### ### ## ##' },
	{ code: '+20', country: 'Egypt', phoneLength: 9, mask: '### ### ####' },
	{ code: '+27', country: 'South Africa', phoneLength: 9, mask: '### ### ####' },
	{ code: '+30', country: 'Greece', phoneLength: 10, mask: '### ### ####' },
	{ code: '+31', country: 'Netherlands', phoneLength: 9, mask: '## ### ####' },
	{ code: '+32', country: 'Belgium', phoneLength: 9, mask: '### ### ###' },
	{ code: '+33', country: 'France', phoneLength: 9, mask: '# ## ## ## ##' },
	{ code: '+34', country: 'Spain', phoneLength: 9, mask: '### ### ###' },
	{ code: '+36', country: 'Hungary', phoneLength: 9, mask: '## ### ####' },
	{ code: '+39', country: 'Italy', phoneLength: 10, mask: '### ### ####' },
	{ code: '+40', country: 'Romania', phoneLength: 9, mask: '### ### ###' },
	{ code: '+41', country: 'Switzerland', phoneLength: 9, mask: '## ### ## ##' },
	{ code: '+44', country: 'United Kingdom', phoneLength: 10, mask: '#### ### ####' },
	{ code: '+45', country: 'Denmark', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+46', country: 'Sweden', phoneLength: 9, mask: '## ### ## ##' },
	{ code: '+47', country: 'Norway', phoneLength: 8, mask: '### ## ###' },
	{ code: '+48', country: 'Poland', phoneLength: 9, mask: '### ### ###' },
	{ code: '+49', country: 'Germany', phoneLength: 10, mask: '#### ### ####' },
	{ code: '+51', country: 'Peru', phoneLength: 9, mask: '### ### ###' },
	{ code: '+52', country: 'Mexico', phoneLength: 10, mask: '## #### ####' },
	{ code: '+53', country: 'Cuba', phoneLength: 8, mask: '### ### ###' },
	{ code: '+54', country: 'Argentina', phoneLength: 10, mask: '### ### ####' },
	{ code: '+55', country: 'Brazil', phoneLength: 11, mask: '## ##### ####' },
	{ code: '+56', country: 'Chile', phoneLength: 9, mask: '## #### ####' },
	{ code: '+57', country: 'Colombia', phoneLength: 10, mask: '### ### ####' },
	{ code: '+58', country: 'Venezuela', phoneLength: 10, mask: '### ### ####' },
	{ code: '+60', country: 'Malaysia', phoneLength: 10, mask: '## ### ####' },
	{ code: '+61', country: 'Australia', phoneLength: 9, mask: '### ### ###' },
	{ code: '+62', country: 'Indonesia', phoneLength: 10, mask: '### ### ####' },
	{ code: '+63', country: 'Philippines', phoneLength: 10, mask: '### ### ####' },
	{ code: '+64', country: 'New Zealand', phoneLength: 9, mask: '### ### ###' },
	{ code: '+65', country: 'Singapore', phoneLength: 8, mask: '#### ####' },
	{ code: '+66', country: 'Thailand', phoneLength: 9, mask: '### ### ###' },
	{ code: '+81', country: 'Japan', phoneLength: 10, mask: '## #### ####' },
	{ code: '+82', country: 'South Korea', phoneLength: 10, mask: '## #### ####' },
	{ code: '+84', country: 'Vietnam', phoneLength: 9, mask: '## ### ####' },
	{ code: '+86', country: 'China', phoneLength: 11, mask: '### #### ####' },
	{ code: '+90', country: 'Turkey', phoneLength: 10, mask: '### ### ## ##' },
	{ code: '+91', country: 'India', phoneLength: 10, mask: '##### #####' },
	{ code: '+92', country: 'Pakistan', phoneLength: 10, mask: '### #### ####' },
	{ code: '+93', country: 'Afghanistan', phoneLength: 9, mask: '## ### ####' },
	{ code: '+94', country: 'Sri Lanka', phoneLength: 9, mask: '### ### ####' },
	{ code: '+95', country: 'Myanmar', phoneLength: 9, mask: '## ### ###' },
	{ code: '+98', country: 'Iran', phoneLength: 10, mask: '### ### ####' },
	{ code: '+212', country: 'Morocco', phoneLength: 9, mask: '### #### ###' },
	{ code: '+213', country: 'Algeria', phoneLength: 9, mask: '### ### ####' },
	{ code: '+216', country: 'Tunisia', phoneLength: 8, mask: '## ### ###' },
	{ code: '+218', country: 'Libya', phoneLength: 9, mask: '### ### ###' },
	{ code: '+220', country: 'Gambia', phoneLength: 8, mask: '### ## ##' },
	{ code: '+221', country: 'Senegal', phoneLength: 9, mask: '## ### ####' },
	{ code: '+222', country: 'Mauritania', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+223', country: 'Mali', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+224', country: 'Guinea', phoneLength: 9, mask: '## ### ####' },
	{ code: '+225', country: 'Ivory Coast', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+226', country: 'Burkina Faso', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+227', country: 'Niger', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+228', country: 'Togo', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+229', country: 'Benin', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+230', country: 'Mauritius', phoneLength: 7, mask: '### ####' },
	{ code: '+231', country: 'Liberia', phoneLength: 7, mask: '## ### ###' },
	{ code: '+232', country: 'Sierra Leone', phoneLength: 8, mask: '## #### ####' },
	{ code: '+233', country: 'Ghana', phoneLength: 9, mask: '### ### ###' },
	{ code: '+234', country: 'Nigeria', phoneLength: 8, mask: '### ### ###' },
	{ code: '+235', country: 'Chad', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+236', country: 'Central African Republic', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+237', country: 'Cameroon', phoneLength: 9, mask: '## ### ####' },
	{ code: '+238', country: 'Cape Verde', phoneLength: 7, mask: '### ####' },
	{ code: '+239', country: 'Sao Tome and Principe', phoneLength: 7, mask: '### ####' },
	{ code: '+240', country: 'Equatorial Guinea', phoneLength: 9, mask: '### ### ####' },
	{ code: '+241', country: 'Gabon', phoneLength: 9, mask: '## ### ####' },
	{ code: '+242', country: 'Republic of the Congo', phoneLength: 9, mask: '## ### ####' },
	{ code: '+243', country: 'Democratic Republic of the Congo', phoneLength: 9, mask: '### ### ####' },
	{ code: '+244', country: 'Angola', phoneLength: 9, mask: '### ### ####' },
	{ code: '+245', country: 'Guinea-Bissau', phoneLength: 7, mask: '### ####' },
	{ code: '+248', country: 'Seychelles', phoneLength: 7, mask: '### ####' },
	{ code: '+249', country: 'Sudan', phoneLength: 9, mask: '### ### ####' },
	{ code: '+250', country: 'Rwanda', phoneLength: 9, mask: '### ### ###' },
	{ code: '+251', country: 'Ethiopia', phoneLength: 9, mask: '### ### ###' },
	{ code: '+252', country: 'Somalia', phoneLength: 8, mask: '### ### ##' },
	{ code: '+253', country: 'Djibouti', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+254', country: 'Kenya', phoneLength: 9, mask: '### ### ###' },
	{ code: '+255', country: 'Tanzania', phoneLength: 9, mask: '### ### ###' },
	{ code: '+256', country: 'Uganda', phoneLength: 9, mask: '### ### ###' },
	{ code: '+257', country: 'Burundi', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+258', country: 'Mozambique', phoneLength: 9, mask: '## ### ####' },
	{ code: '+260', country: 'Zambia', phoneLength: 9, mask: '### ### ###' },
	{ code: '+261', country: 'Madagascar', phoneLength: 9, mask: '## ## ###' },
	{ code: '+262', country: 'Réunion', phoneLength: 9, mask: '### ### ###' },
	{ code: '+263', country: 'Zimbabwe', phoneLength: 9, mask: '### ### ###' },
	{ code: '+264', country: 'Namibia', phoneLength: 9, mask: '### ### ###' },
	{ code: '+265', country: 'Malawi', phoneLength: 9, mask: '### ### ###' },
	{ code: '+266', country: 'Lesotho', phoneLength: 8, mask: '## ### ###' },
	{ code: '+267', country: 'Botswana', phoneLength: 8, mask: '## ### ###' },
	{ code: '+268', country: 'Eswatini', phoneLength: 9, mask: '### ### ###' },
	{ code: '+269', country: 'Comoros', phoneLength: 7, mask: '### ####' },
]
