export const indicatifs = [
	{ code: '+1', country: 'USA/Canada', abbreviation: 'US/CA', phoneLength: 10, mask: '### ### ####' },
	{ code: '+7', country: 'Russia/Kazakhstan', abbreviation: 'RU/KZ', phoneLength: 10, mask: '### ### ## ##' },
	{ code: '+20', country: 'Egypt', abbreviation: 'EG', phoneLength: 9, mask: '### ### ####' },
	{ code: '+27', country: 'South Africa', abbreviation: 'ZA', phoneLength: 9, mask: '### ### ####' },
	{ code: '+30', country: 'Greece', abbreviation: 'GR', phoneLength: 10, mask: '### ### ####' },
	{ code: '+31', country: 'Netherlands', abbreviation: 'NL', phoneLength: 9, mask: '## ### ####' },
	{ code: '+32', country: 'Belgium', abbreviation: 'BE', phoneLength: 9, mask: '### ### ###' },
	{ code: '+33', country: 'France', abbreviation: 'FR', phoneLength: 10, mask: '## ## ## ## ##' },
	{ code: '+34', country: 'Spain', abbreviation: 'ES', phoneLength: 9, mask: '### ### ###' },
	{ code: '+36', country: 'Hungary', abbreviation: 'HU', phoneLength: 9, mask: '## ### ####' },
	{ code: '+39', country: 'Italy', abbreviation: 'IT', phoneLength: 10, mask: '### ### ####' },
	{ code: '+40', country: 'Romania', abbreviation: 'RO', phoneLength: 9, mask: '### ### ###' },
	{ code: '+41', country: 'Switzerland', abbreviation: 'CH', phoneLength: 9, mask: '## ### ## ##' },
	{ code: '+44', country: 'United Kingdom', abbreviation: 'GB', phoneLength: 10, mask: '#### ### ####' },
	{ code: '+45', country: 'Denmark', abbreviation: 'DK', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+46', country: 'Sweden', abbreviation: 'SE', phoneLength: 9, mask: '## ### ## ##' },
	{ code: '+47', country: 'Norway', abbreviation: 'NO', phoneLength: 8, mask: '### ## ###' },
	{ code: '+48', country: 'Poland', abbreviation: 'PL', phoneLength: 9, mask: '### ### ###' },
	{ code: '+49', country: 'Germany', abbreviation: 'DE', phoneLength: 10, mask: '#### ### ####' },
	{ code: '+51', country: 'Peru', abbreviation: 'PE', phoneLength: 9, mask: '### ### ###' },
	{ code: '+52', country: 'Mexico', abbreviation: 'MX', phoneLength: 10, mask: '## #### ####' },
	{ code: '+53', country: 'Cuba', abbreviation: 'CU', phoneLength: 8, mask: '### ### ###' },
	{ code: '+54', country: 'Argentina', abbreviation: 'AR', phoneLength: 10, mask: '### ### ####' },
	{ code: '+55', country: 'Brazil', abbreviation: 'BR', phoneLength: 11, mask: '## ##### ####' },
	{ code: '+56', country: 'Chile', abbreviation: 'CL', phoneLength: 9, mask: '## #### ####' },
	{ code: '+57', country: 'Colombia', abbreviation: 'CO', phoneLength: 10, mask: '### ### ####' },
	{ code: '+58', country: 'Venezuela', abbreviation: 'VE', phoneLength: 10, mask: '### ### ####' },
	{ code: '+60', country: 'Malaysia', abbreviation: 'MY', phoneLength: 10, mask: '## ### ####' },
	{ code: '+61', country: 'Australia', abbreviation: 'AU', phoneLength: 9, mask: '### ### ###' },
	{ code: '+62', country: 'Indonesia', abbreviation: 'ID', phoneLength: 10, mask: '### ### ####' },
	{ code: '+63', country: 'Philippines', abbreviation: 'PH', phoneLength: 10, mask: '### ### ####' },
	{ code: '+64', country: 'New Zealand', abbreviation: 'NZ', phoneLength: 9, mask: '### ### ###' },
	{ code: '+65', country: 'Singapore', abbreviation: 'SG', phoneLength: 8, mask: '#### ####' },
	{ code: '+66', country: 'Thailand', abbreviation: 'TH', phoneLength: 9, mask: '### ### ###' },
	{ code: '+81', country: 'Japan', abbreviation: 'JP', phoneLength: 10, mask: '## #### ####' },
	{ code: '+82', country: 'South Korea', abbreviation: 'KR', phoneLength: 10, mask: '## #### ####' },
	{ code: '+84', country: 'Vietnam', abbreviation: 'VN', phoneLength: 9, mask: '## ### ####' },
	{ code: '+86', country: 'China', abbreviation: 'CN', phoneLength: 11, mask: '### #### ####' },
	{ code: '+90', country: 'Turkey', abbreviation: 'TR', phoneLength: 10, mask: '### ### ## ##' },
	{ code: '+91', country: 'India', abbreviation: 'IN', phoneLength: 10, mask: '##### #####' },
	{ code: '+92', country: 'Pakistan', abbreviation: 'PK', phoneLength: 10, mask: '### #### ####' },
	{ code: '+93', country: 'Afghanistan', abbreviation: 'AF', phoneLength: 9, mask: '## ### ####' },
	{ code: '+94', country: 'Sri Lanka', abbreviation: 'LK', phoneLength: 9, mask: '### ### ####' },
	{ code: '+95', country: 'Myanmar', abbreviation: 'MM', phoneLength: 9, mask: '## ### ###' },
	{ code: '+98', country: 'Iran', abbreviation: 'IR', phoneLength: 10, mask: '### ### ####' },
	{ code: '+212', country: 'Morocco', abbreviation: 'MA', phoneLength: 9, mask: '### #### ###' },
	{ code: '+213', country: 'Algeria', abbreviation: 'DZ', phoneLength: 9, mask: '### ### ####' },
	{ code: '+216', country: 'Tunisia', abbreviation: 'TN', phoneLength: 8, mask: '## ### ###' },
	{ code: '+218', country: 'Libya', abbreviation: 'LY', phoneLength: 9, mask: '### ### ###' },
	{ code: '+262', country: 'Réunion', abbreviation: 'FR', phoneLength: 9, mask: '### ### ###' },
	{ code: '+508', country: 'Saint Pierre and Miquelon', abbreviation: 'FR', phoneLength: 6, mask: '## ## ##' },
	{ code: '+590', country: 'Guadeloupe', abbreviation: 'FR', phoneLength: 9, mask: '### ### ###' },
	{ code: '+594', country: 'French Guiana', abbreviation: 'FR', phoneLength: 9, mask: '### ### ###' },
	{ code: '+596', country: 'Martinique', abbreviation: 'FR', phoneLength: 9, mask: '### ### ###' },
	{ code: '+687', country: 'New Caledonia', abbreviation: 'FR', phoneLength: 6, mask: '## ## ##' },
	{ code: '+689', country: 'French Polynesia', abbreviation: 'FR', phoneLength: 6, mask: '## ## ##' },
	{ code: '+220', country: 'Gambia', abbreviation: 'GM', phoneLength: 8, mask: '### ## ##' },
	{ code: '+221', country: 'Senegal', abbreviation: 'SN', phoneLength: 9, mask: '## ### ####' },
	{ code: '+222', country: 'Mauritania', abbreviation: 'MR', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+223', country: 'Mali', abbreviation: 'ML', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+224', country: 'Guinea', abbreviation: 'GN', phoneLength: 9, mask: '## ### ####' },
	{ code: '+225', country: 'Ivory Coast', abbreviation: 'CI', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+226', country: 'Burkina Faso', abbreviation: 'BF', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+227', country: 'Niger', abbreviation: 'NE', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+228', country: 'Togo', abbreviation: 'TG', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+229', country: 'Benin', abbreviation: 'BJ', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+230', country: 'Mauritius', abbreviation: 'MU', phoneLength: 7, mask: '### ####' },
	{ code: '+231', country: 'Liberia', abbreviation: 'LR', phoneLength: 7, mask: '## ### ###' },
	{ code: '+232', country: 'Sierra Leone', abbreviation: 'SL', phoneLength: 8, mask: '## #### ####' },
	{ code: '+233', country: 'Ghana', abbreviation: 'GH', phoneLength: 9, mask: '### ### ###' },
	{ code: '+234', country: 'Nigeria', abbreviation: 'NG', phoneLength: 8, mask: '### ### ###' },
	{ code: '+235', country: 'Chad', abbreviation: 'TD', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+236', country: 'Central African Republic', abbreviation: 'CF', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+237', country: 'Cameroon', abbreviation: 'CM', phoneLength: 9, mask: '## ### ####' },
	{ code: '+238', country: 'Cape Verde', abbreviation: 'CV', phoneLength: 7, mask: '### ####' },
	{ code: '+239', country: 'Sao Tome and Principe', abbreviation: 'ST', phoneLength: 7, mask: '### ####' },
	{ code: '+240', country: 'Equatorial Guinea', abbreviation: 'GQ', phoneLength: 9, mask: '### ### ####' },
	{ code: '+241', country: 'Gabon', abbreviation: 'GA', phoneLength: 9, mask: '## ### ####' },
	{ code: '+242', country: 'Republic of the Congo', abbreviation: 'CG', phoneLength: 9, mask: '## ### ####' },
	{ code: '+243', country: 'Democratic Republic of the Congo', abbreviation: 'CD', phoneLength: 9, mask: '### ### ####' },
	{ code: '+244', country: 'Angola', abbreviation: 'AO', phoneLength: 9, mask: '### ### ####' },
	{ code: '+245', country: 'Guinea-Bissau', abbreviation: 'GW', phoneLength: 7, mask: '### ####' },
	{ code: '+248', country: 'Seychelles', abbreviation: 'SC', phoneLength: 7, mask: '### ####' },
	{ code: '+249', country: 'Sudan', abbreviation: 'SD', phoneLength: 9, mask: '### ### ####' },
	{ code: '+250', country: 'Rwanda', abbreviation: 'RW', phoneLength: 9, mask: '### ### ###' },
	{ code: '+251', country: 'Ethiopia', abbreviation: 'ET', phoneLength: 9, mask: '### ### ###' },
	{ code: '+252', country: 'Somalia', abbreviation: 'SO', phoneLength: 8, mask: '### ### ##' },
	{ code: '+253', country: 'Djibouti', abbreviation: 'DJ', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+254', country: 'Kenya', abbreviation: 'KE', phoneLength: 9, mask: '### ### ###' },
	{ code: '+255', country: 'Tanzania', abbreviation: 'TZ', phoneLength: 9, mask: '### ### ###' },
	{ code: '+256', country: 'Uganda', abbreviation: 'UG', phoneLength: 9, mask: '### ### ###' },
	{ code: '+257', country: 'Burundi', abbreviation: 'BI', phoneLength: 8, mask: '## ## ## ##' },
	{ code: '+258', country: 'Mozambique', abbreviation: 'MZ', phoneLength: 9, mask: '## ### ####' },
	{ code: '+260', country: 'Zambia', abbreviation: 'ZM', phoneLength: 9, mask: '### ### ###' },
	{ code: '+261', country: 'Madagascar', abbreviation: 'MG', phoneLength: 9, mask: '## ## ###' },
	{ code: '+263', country: 'Zimbabwe', abbreviation: 'ZW', phoneLength: 9, mask: '### ### ###' },
	{ code: '+264', country: 'Namibia', abbreviation: 'NA', phoneLength: 9, mask: '### ### ###' },
	{ code: '+265', country: 'Malawi', abbreviation: 'MW', phoneLength: 9, mask: '### ### ###' },
	{ code: '+266', country: 'Lesotho', abbreviation: 'LS', phoneLength: 8, mask: '## ### ###' },
	{ code: '+267', country: 'Botswana', abbreviation: 'BW', phoneLength: 8, mask: '## ### ###' },
	{ code: '+268', country: 'Eswatini', abbreviation: 'SZ', phoneLength: 9, mask: '### ### ###' },
	{ code: '+269', country: 'Comoros', abbreviation: 'KM', phoneLength: 7, mask: '### ####' },
]
